/* MemeLab Watchlist — dedicated renderer. */
(()=>{
const $=s=>document.querySelector(s),life=t=>t?.lifecycle||"DISCOVERED",stats=t=>t?.stats_24h||{};
const tradesPerTrader=(trades,traders)=>{const t=Number(trades),n=Number(traders);if(!Number.isFinite(t)||!Number.isFinite(n)||n<=0)return null;return t/n};const ratioFmt=v=>{if(v==null)return"—";if(v>=1e6)return(v/1e6).toFixed(1)+"M";if(v>=1e3)return(v/1e3).toFixed(1)+"K";if(v>=100)return v.toFixed(0);if(v>=10)return v.toFixed(1);return v.toFixed(2)};const dateFmt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toISOString().slice(0,10)};const mint=m=>!m?"—":m.length<=14?m:m.slice(0,7)+"…"+m.slice(-5);
const usd=v=>{const n=Number(v);if(!Number.isFinite(n))return"—";if(Math.abs(n)>=1e9)return"$"+(n/1e9).toFixed(2)+"B";if(Math.abs(n)>=1e6)return"$"+(n/1e6).toFixed(2)+"M";if(Math.abs(n)>=1e3)return"$"+(n/1e3).toFixed(1)+"K";if(Math.abs(n)>=1)return"$"+n.toFixed(2);return"$"+n.toExponential(2)};
let rows=[],sortKey="liquidity",sortDir="desc";
const val=(t,k)=>{const m=t?.monitoring||{},s=stats(t);if(k==="symbol")return String(t.symbol||"").toLowerCase();if(k==="lifecycle")return life(t);if(k==="liquidity")return Number(t.liquidity||0);if(k==="volume")return Number(s.volume||0);if(k==="trades")return Number(m.trades_24h??(Number(s.num_buys||0)+Number(s.num_sells||0)));if(k==="traders")return Number(s.num_traders||0);if(k==="trades_per_trader"){const trades=m.trades_24h??(Number(s.num_buys||0)+Number(s.num_sells||0));return tradesPerTrader(trades,s.num_traders)??-1;}if(k==="created"){return String(t.created_at||t.createdAt||"")}if(k==="last_activity"){return String(t.last_activity||t.last_activity_at||t.lastActivity||"")}if(k==="organic")return Number(t.organic_score||0);if(k==="active_12")return Number(m.active_observations_last_12||0);if(k==="observations")return Number(m.observations||0);if(k==="next_status")return String(m.next_status||life(t));return 0};
function render(){const root=$("#watchlist-root");if(!root)return;const list=rows.filter(t=>life(t)==="ACTIVE"||life(t)==="MATURE");list.sort((a,b)=>{const av=val(a,sortKey),bv=val(b,sortKey),c=(typeof av==="string"||typeof bv==="string")?String(av).localeCompare(String(bv)):av-bv;return sortDir==="asc"?c:-c});
const h=[["symbol","Token"],["lifecycle","Lifecycle"],["created","Created"],["last_activity","Last Activity"],["liquidity","Liquidity"],["volume","24h Volume"],["trades","Trades"],["traders","Traders"],["trades_per_trader","Trades/Trader"],["organic","Organic"],["observations","Observations"]];
const table=document.createElement("table");table.className="watchlist-table";const hr=document.createElement("tr");h.forEach(([k,label])=>{const th=document.createElement("th"),b=document.createElement("button");b.type="button";b.dataset.sort=k;b.textContent=label;b.onclick=()=>{if(sortKey===k)sortDir=sortDir==="asc"?"desc":"asc";else{sortKey=k;sortDir=["symbol","lifecycle","next_status"].includes(k)?"asc":"desc"}render()};th.appendChild(b);hr.appendChild(th)});const thead=document.createElement("thead");thead.appendChild(hr);table.appendChild(thead);
const tbody=document.createElement("tbody");if(!list.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=11;td.className="watchlist-empty";td.textContent="Noch keine ACTIVE- oder MATURE-Tokens.";tr.appendChild(td);tbody.appendChild(tr)}else list.forEach(t=>{const m=t.monitoring||{},s=stats(t),trades=m.trades_24h??(Number(s.num_buys||0)+Number(s.num_sells||0)),cells=['<strong>'+(t.symbol||mint(t.mint))+'</strong><small>'+(t.name||"—")+'</small>',t.lifecycle||"—",dateFmt(t.created_at||t.createdAt),dateFmt(t.last_activity||t.last_activity_at||t.lastActivity),usd(t.liquidity),usd(s.volume),trades||"—",s.num_traders??"—",ratioFmt(tradesPerTrader(trades,s.num_traders)),t.organic_score!=null?Number(t.organic_score).toFixed(0):"—",m.observations??"—"];const tr=document.createElement("tr");tr.dataset.token=t.mint||"";cells.forEach((x,i)=>{const td=document.createElement("td");td.innerHTML=x;if(i===10)td.className="next ready";tr.appendChild(td)});tr.onclick=()=>window.MEMELAB_MARKET?.selectToken?.(t.mint);tbody.appendChild(tr)});table.appendChild(tbody);root.replaceChildren(table);const c=$("#watchlist-count");if(c)c.textContent=String(list.length)}
function update(d){rows=Array.isArray(d?.diagnostics?.watchlist)?d.diagnostics.watchlist:[];render()}window.addEventListener("memelab:jupiter-data",e=>update(e.detail));if(window.MEMELAB_JUPITER_DATA)update(window.MEMELAB_JUPITER_DATA);
})();
